### PR TITLE
Additional Studio Logos

### PR DESCRIPTION
**Pull request by KarellenX**
My first PR. Please let me know if any errors

15 new coloured studio logos added

### CODE REVIEW

**Comment by monisriz** [comment]
Might need to change the file names to uppercase for the 1st letter of each word. Some OS/file-systems are case sensitive and the logos might not show up if the scraper/nfo has the studio listed in a different case than the files here..

**Comment by KarellenX** [comment]
Thanks @monisriz and @ronie 

Hopefully this is all correct.

**Comment by KarellenX** [comment]
Hopefully cleaned up the mess ;)

**Comment by monisriz** [comment]
A transparent logo for Red Granite Pictures is already in the repo. Is there a reason why you want to replace it? Transparent logos are better, in my opinion, as they can work with any skin. A logo with solid background color would, however, might look out of place on a different skin.

**Comment by KarellenX** [comment]
Nope, no reason. Missed it when I searched through it. I'll remove it.

**Comment by ronie** [comment]
thx!

**Pull request merged**
