### PR TITLE
Adding Color Logos to Studio Incons - Color Version 0.0.23

### PR DESCRIPTION
**Pull request by OnyxHub**
abc pictures

altitude film distribution

audax films

brazzers

entertainment partners ltd

focus world

gravitas ventures

haviland digital

hays films

head gear films

imperative entertainment

jour2fete

jour2fete distribution

legion m

mark stewart productions

mark stewart productions ltd

park pictures

rlje films

rough house pictures

spectrevision

### CODE REVIEW

**Comment by ronie** [comment]
sorry, i'm unable to merge this PR as it has (many) errors.

**Comment by OnyxGhub** [comment]
@ronie Thanks for the update. What exactly are the errors you're referring to?  The "Textures.xbt" file I was able to create with these included images has produced no errors, so I'm curious to learn what is causing errors.

Thank you

**Comment by Slim1399** [comment]
Qatar TV:  qatar_tv_logo_

MBC:  Mbc1logo

**Comment by KarellenX** [comment]
@Slim1399 

You would be better off creating a new PR rather than adding to a closed one. Do you know how to create a PR for submission?

Your images need to satisfy these requirements... https://github.com/XBMC-Addons/resource.images.studios.coloured/issues/13#issuecomment-464534085

**Comment by Slim1399** [comment]
@KarellenX 
I'm new her, i don't know yet how to create a PR !

**Pull request closed without merging**
