### PR TITLE
new logos

### PR DESCRIPTION
**Pull request by monisriz**

### CODE REVIEW

**Comment by ronie** [comment]
thx

**Comment by monisriz** [comment]
Can you plz merge these to the addon repo? It’s been a while since the last update..

**Comment by ronie** [comment]
there are close to 7000 logos in this addon. since the last update, two new logos have been added and a few were updated. sorry but that's just not enough to warrant an update.

**Comment by monisriz** [comment]
The frequency of new logos being added is bound to decrease as the number of logos in this addon increases - there are only so many studios after all :)
What number of changes would/should warrant an update? And what’s the downside of a more frequent update schedule?

**Comment by ronie** [comment]
i prefer not to bother users with frequent addon updates, especially not with big ones like this.

if there's 100 new logos, i would update it straight away.
if there's only 1, i would wait till the next kodi release.

**Pull request merged**
